const FUNCTIONS = new Map([
    ["sceneStart", {params: {min: 0, max: 0}}],
    ["sceneEnd", {params: {min: 0, max: 0}}],
    ["addColleague", {params: {min: 0, max: 0}}],
    ["addDatingFriend", {params: {min: 0, max: 0}}],
    ["addNeighbour", {params: {min: 0, max: 0}}],
    ["blendPreset", {params: {min: 0, max: 0}}],
    ["blockContact", {params: {min: 0, max: 0}}],
    ["clearGlobal", {params: {min: 0, max: 0}}],
    ["closeEyes", {params: {min: 0, max: 0}}],
    ["convertToLocalCurrency", {params: {min: 0, max: 0}}],
    ["delete", {params: {min: 0, max: 0}}],
    ["Divorce", {params: {min: 0, max: 0}}],
    ["dress", {params: {min: 0, max: 0}}],
    ["endDate", {params: {min: 0, max: 0}}],
    ["exchangeContact", {params: {min: 0, max: 0}}],
    ["Filter", {params: {min: 0, max: 0}}],
    ["forgiveAffairs", {params: {min: 0, max: 0}}],
    ["generatePerson", {params: {min: 0, max: 0}}],
    ["generatePersonTemporary", {params: {min: 0, max: 0}}],
    ["getCompanion", {params: {min: 0, max: 0}}],
    ["getGlobal", {params: {min: 0, max: 0}}],
    ["getID", {params: {min: 0, max: 0}}],
    ["getMarried", {params: {min: 0, max: 0}}],
    ["getPerson", {params: {min: 0, max: 0}}],
    ["getRelative", {params: {min: 0, max: 0}}],
    ["getRelativeExcept", {params: {min: 0, max: 0}}],
    ["getRent", {params: {min: 0, max: 0}}],
    ["getSalary", {params: {min: 0, max: 0}}],
    ["getSpecific", {params: {min: 0, max: 0}}],
    ["hide", {params: {min: 0, max: 0}}],
    ["loseDating", {params: {min: 0, max: 0}}],
    ["loseHome", {params: {min: 0, max: 0}}],
    ["loseHomeDating", {params: {min: 0, max: 0}}],
    ["loseJob", {params: {min: 0, max: 0}}],
    ["losePT", {params: {min: 0, max: 0}}],
    ["makePermanent", {params: {min: 0, max: 0}}],
    ["moveHome", {params: {min: 0, max: 0}}],
    ["moveJobs", {params: {min: 0, max: 0}}],
    ["moveTo", {params: {min: 0, max: 0}}],
    ["passTime", {params: {min: 0, max: 0}}],
    ["Random(", {params: {min: 0, max: 0}}],
    ["randomizeFace", {params: {min: 0, max: 0}}],
    ["randomizeHairs", {params: {min: 0, max: 0}}],
    ["removeColleague", {params: {min: 0, max: 0}}],
    ["removeDatingFriend", {params: {min: 0, max: 0}}],
    ["removeNeighbour", {params: {min: 0, max: 0}}],
    ["setBackground", {params: {min: 0, max: 0}}],
    ["setBoss", {params: {min: 0, max: 0}}],
    ["setDating", {params: {min: 0, max: 0}}],
    ["setGlobal", {params: {min: 0, max: 0}}],
    ["setHomeCity", {params: {min: 0, max: 0}}],
    ["setLandlord", {params: {min: 0, max: 0}}],
    ["setLivingWithPlayer", {params: {min: 0, max: 0}}],
    ["setPT", {params: {min: 0, max: 0}}],
    ["setRent", {params: {min: 0, max: 0}}],
    ["setSalary", {params: {min: 0, max: 0}}],
    ["Sex", {params: {min: 0, max: 0}}],
    ["SexNoAffair", {params: {min: 0, max: 0}}],
    ["show", {params: {min: 0, max: 0}}],
    ["startDate", {params: {min: 0, max: 0}}],
    ["strip", {params: {min: 0, max: 0}}],
    ["TalkNonConsensual", {params: {min: 0, max: 0}}],
    ["timeout", {params: {min: 0, max: 0}}],
    ["timeoutActor", {params: {min: 0, max: 0}}],
    ["timeoutprecise", {params: {min: 0, max: 0}}],
    ["timeoutActorPrecise", {params: {min: 0, max: 0}}],
    // undocumented
    ["secondScreen", {params: {min: 0, max: 0}}],
    ["getDaddy", {params: {min: 0, max: 0}}],
    ["blockPregnancy", {params: {min: 0, max: 0}}],
    ["addNpcRelationship", {params: {min: 3, max: 3}}],
    ["removeNpcRelationship", {params: {min: 2, max: 2}}],
    ["followUp", {params: {min: 1, max: 1}}],
    ["setBackgroundCustom", {params: {min: 1, max: 1}}],
    ["dressFormal", {params: {min: 0, max: 0}}],
    ["selectNPC", {params: {min: 0, max: 0}}],
    ["QuestEnd", {params: {min: 0, max: 0}}],
    ["AnimatePair", {params: {min: 3, max: 3}}],
    ["chooseContact", {params: {min: 0, max: 1}}],
    ["sneakGame", {params: {min: 0, max: 0}}],
    ["faceEachOther", {params: {min: 2, max: 2}}],
    ["TalkNonConcensual", {params: {min: 0, max: 0}}],

    // unverified
    ["chooseMajor", {params: {min: 0, max: 0}}],
    ["setMajor", {params: {min: 0, max: 0}}],
    ["ResetTutorials", {params: {min: 0, max: 0}}],
    ["OpenMenu", {params: {min: 1, max: 1}}],
    ["SaveOldPlayer", {params: {min: 0, max: 0}}],
    ["SecondScreenIfHidden", {params: {min: 1, max: 1}}],
    ["quitCrime", {params: {min: 0, max: 0}}],
    ["quitFraternity", {params: {min: 0, max: 0}}],
    ["quitLecturing", {params: {min: 0, max: 0}}],
    ["quitMedical", {params: {min: 0, max: 0}}],
    ["quitSchool", {params: {min: 0, max: 0}}],
    ["removeAddedClothes", {params: {min: 0, max: 0}}],
    ["PreciseModify", {params: {min: 0, max: 0}}],
    ["startOpenRelationship", {params: {min: 0, max: 0}}],
    ["endOpenRelationship", {params: {min: 0, max: 0}}],
    ["endPrison", {params: {min: 0, max: 0}}],
    ["sceneEndLoadLastSave", {params: {min: 0, max: 0}}],
    ["contractSTD", {params: {min: 0, max: 0}}],
    ["startBusiness", {params: {min: 0, max: 0}}],
    ["enterBusinessName", {params: {min: 0, max: 0}}],
    ["ModifyReputation", {params: {min: 0, max: 0}}],
    ["stopBusiness", {params: {min: 0, max: 0}}],
    ["setBackground3D", {params: {min: 1, max: 1}}],
    ["FilterTalk", {params: {min: 1, max: 1}}],
    ["LoseDatingIncoming", {params: {min: 0, max: 0}}],
    ["clearGetList", {params: {min: 0, max: 0}}],
    ["cameraFocus", {params: {min: 1, max: 3}}],
    ["AssignResidents", {params: {min: 0, max: 0}}],
    ["cameraMove", {params: {min: 0, max: 0}}],
])
const STATS = [
    "age",
    "arousal",
    "attractiontoplayer",
    "attractiveness",
    "car_value",
    "children",
    "cooking",
    "dance",
    "energy",
    "fertility",
    "fitness",
    "incest",
    "intelligence",
    "interpersonal",
    "intoxication",
    "jobexperience",
    "jobperformance",
    "martial",
    "masochist",
    "money",
    "mood",
    "muscle",
    "music",
    "perversion",
    "pet_health",
    "pornfame",
    "rapportwithplayer",
    "sneak",
    "stock_alcohol",
    "stock_book",
    "stock_coffee",
    "stock_condom",
    "stock_flower",
    "stock_gift",
    "stock_haircare",
    "stock_ingredient",
    "stock_juice",
    "stock_makeup",
    "stock_meal",
    "stock_movie",
    "stock_musicalinstrument",
    "stock_petfood",
    "stock_photo",
    "stock_pill",
    "stock_skincare",
    "stock_snack",
    "stock_soda",
    "stock_supplement",
    "stock_tea",
    "stock_tobacco",
    "stock_video"
]
const LOCATIONS = [
    "art",
    "bag",
    "bakery",
    "bank",
    "bar",
    "beauty",
    "beverages",
    "bicycle",
    "biergarten",
    "books",
    "butcher",
    "cafe",
    "car",
    "chemist",
    "cinema",
    "clothes",
    "coffee",
    "community_centre",
    "computer",
    "confectionery",
    "convenience",
    "copyshop",
    "cosmetics",
    "deli",
    "dentist",
    "department_store",
    "doctor",
    "doityourself",
    "electronics",
    "fast_food",
    "florist",
    "furniture",
    "garden_centre",
    "gift",
    "greengrocer",
    "hairdresser",
    "hospital",
    "hotel",
    "ice_cream",
    "jewellery",
    "laundry",
    "library",
    "marketplace",
    "mobile_phone",
    "motorcycle",
    "musical_instrument",
    "newsagent",
    "nightclub",
    "office",
    "optician",
    "outdoor",
    "pet",
    "pharmacy",
    "photo",
    "place_of_worship",
    "police",
    "post_office",
    "prison",
    "pub",
    "residential",
    "restaurant",
    "seafood",
    "shoes",
    "sports",
    "sports_centre",
    "stationery",
    "supermarket",
    "tea",
    "theatre",
    "tobacco",
    "toilets",
    "toys",
    "travel_agency",
    "variety_store",
    "veterinary"
]
const MOODS = [
    "Angry",
    "Annoyed",
    "Anxious",
    "Attentive",
    "Bored",
    "Confused",
    "Crying",
    "Curious",
    "Disgusted",
    "Drained",
    "Embarassed",
    "Embarrassed",
    "Evil",
    "Excited",
    "Flirty",
    "Furious",
    "Grin",
    "Irritated",
    "Kiss",
    "Lazy",
    "Offended",
    "Pain",
    "Peaceful",
    "Posing",
    "Sarcastic",
    "Scared",
    "Serene",
    "Shocked",
    "Shy",
    "Surprised",
    "Wink",
    "Sad",
    "Happy",
    "Tired"
]
const SEX_TAGS = [
    "Solo",
    "Couple",
    "MF",
    "FF",
    "Threesome",
    "MM",
    "MMF",
    "MFF",
    "FFF",
    "MMMM",
    "MMMF",
    "MMFF",
    "MFFF",
    "FFFF",
    "Fivesome",
    "MMMMM",
    "MMMMF",
    "MMMFF",
    "MMFFF",
    "MFFFF",
    "FFFFF",
    "Gay",
    "Lesbian",
    "Bisexual",
    "Group",
    "Gangbang",
    "ReverseGangbang",
    "Foreplay",
    "Oral",
    "Blowjob",
    "Licking",
    "Boobjob",
    "LickingBoobs",
    "MutualMasturbation",
    "69",
    "Fingering",
    "Handjob",
    "Fisting",
    "NonSexual",
    "Kissing",
    "Hugging",
    "Penetration",
    "Vaginal",
    "Anal",
    "Standing",
    "Sitting",
    "Lying",
    "Kneeling",
    "Doggy",
    "Missionary",
    "Cowgirl",
    "ReverseCowgirl",
    "Sideways",
    "Aggressive"
]
const OPERATORS = [
    "-",
    ".",
    "[",
    "]",
    "(",
    ")",
    "*",
    "/",
    "+",
    "<",
    "=",
    ">",
    "|",
    ":",
    "&",
    "!",
    ";"
]
const ACTOR_FUNCTIONS = [
    "DatingHasHome",
    "ForcedTrigger",
    "isAffair",
    "isAsexual",
    "isAtDatingHome",
    "isAtHome",
    "isBoss",
    "isColleague",
    "isContactExchanged",
    "isDating",
    "isDatingFriend",
    "isDominantSex",
    "isEquipped",
    "isInterestedIn",
    "isLandlord",
    "isMale",
    "isMarried",
    "isModEnabled",
    "isNeighbour",
    "isPlayer",
    "isPlayerMarried",
    "isRelative",
    "isSameAs",
    "isSameGender",
    "isValid",
    "isVisible",
    "isWithCompanion",
    "livesWithPlayer",
    "PlayerHasHome",
    "Tag"
]
const OBJECTS = ["Player", "CurrentCompanion"]
const PROPERTY = ["actionDuration", "Difficulty", "CostOfLiving"]

module.exports = {
    FUNCTIONS,
    L_FUNCTIONS: Array.from(FUNCTIONS.keys()).map(e => e.toLowerCase()),
    ACTOR_FUNCTIONS,
    STATS,
    LOCATIONS,
    MOODS,
    SEX_TAGS,
    OPERATORS,
    OBJECTS,
    PROPERTY,
}